apiVersion: v1
kind: Service
metadata:
  name: pks-galera
  labels:
    app: drupal-galera
    tier: backend
spec:
  ports:
  - port: 3306
  selector:
    app: drupal-galera
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal-galera
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: drupal-galera
        tier: backend
    spec:
      containers:
      - name: drupal-galera
        image: nvpnathan/drupal-galera
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-frontend-svc
  labels:
    app: drupal-frontend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: drupal-frontend
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal-frontend
  labels:
    app: drupal-frontend
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drupal-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: drupal-frontend
        tier: frontend
    spec:
      containers:
      - name: drupal-frontend
        image: nvpnathan/drupal-frontend
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
